version: "3"
services:
  db:
    image: postgres:16-bookworm
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - db_store:/var/lib/postgresql/data
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}

volumes:
  db_store:
