[tasks.dotenv]
script_runner = "@rust"
script = '''
//! ```cargo
//! [dependencies]
//! dotenvy = "0.15.7"
//! ```
use std::io::Write;
use std::fs;
use std::env;
use std::path;
fn main() {
    dotenvy::dotenv().unwrap();

    let host = env::var("DB_HOST").unwrap();
    let port = env::var("DB_PORT").unwrap();
    let name = env::var("DB_NAME").unwrap();
    let user = env::var("DB_USER").unwrap();
    let password = env::var("DB_PASSWORD").unwrap();

    // use localhost here because we are using docker-compose for db, and running web_backend locally
    let database_url = format!("postgres://{user}:{password}@localhost:{port}/{name}");

    let dotenv_contents = format!("DATABASE_URL='{}'\n", database_url);
    
    let path = env::current_dir().unwrap();
    println!("starting dir: {}", path.display());
    let dotenv_path = path::Path::new("web_backend/.env");
    let mut file = fs::File::create(dotenv_path).unwrap();
    
    file.write_all(dotenv_contents.as_bytes()).unwrap();
}
'''
